version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
plugins:
  brakeman:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-6
    config:
      config: .eslintrc.json
  rubocop:
    enabled: true
    channel: rubocop-0-89
  fixme:
    enabled: true
