inherit_from: .rubocop_todo.yml

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - require_relative
    - puts
    - raise
    - rescue_from
    - render
    - redirect_to
    - send_data
    - mail
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.jbuilder'
    - 'Gemfile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'feature'
    - 'describe'
    - 'context'
    - 'scenario'
    - 'draw'
    - 'configure'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
