inherit_from: .rubocop_todo.yml

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - require_relative
    - puts
    - rescue_from
    - render
    - redirect_to
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.jbuilder'
    - 'Gemfile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'feature'
    - 'describe'
    - 'context'
    - 'draw'

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
