inherit_from: .rubocop_todo.yml

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - require_relative
    - puts
    - rescue_from
    - render
    - redirect_to
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.jbuilder'
    - 'Gemfile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
