# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

commands:
  setupapp:
    steps:
      # https://support.circleci.com/hc/en-us/articles/360004086734-error-while-loading-shared-libraries-libgconf-2-so-4-cannot-open-shared-object-file-No-such-file-or-directory
      - run:
          command: |
            sudo apt-get install libgconf-2-4

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: myapp
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp-test
          POSTGRES_PASSWORD: ""
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - setupapp
        
      - run:
          name: Wait for database to become available
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Setup database
          command: bin/rake db:create db:schema:load

      - run:
          name: Run Rspec
          command: bin/rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    steps:
      - setupapp

      - run:
          name: Run Rubocop
          command: bin/rubocop
workflows:
  version: 2
  all:
    jobs:
      - rspec
      - rubocop
